- name: Get latest version of plugin
  become: true
  ansible.builtin.uri:
    url: https://plugins.jetbrains.com/api/plugins/{{ pycharm_plugin }}/updates
  register: pycharm_plugin_version
  changed_when: false

- name: Download plugin
  become: true
  ansible.builtin.get_url:
    url: "https://plugins.jetbrains.com/files/{{ pycharm_plugin_version.json[0].file }}"
    dest: "/tmp/pycharm-plugin-{{ pycharm_plugin }}.zip"
    mode: 0644

- name: Extract plugin to directory
  become: true
  become_user: "{{ pycharm_user }}"
  ansible.builtin.unarchive:
    src: "/tmp/pycharm-plugin-{{ pycharm_plugin }}.zip"
    dest: "~/.local/share/JetBrains/PyCharm{{ pycharm_naming_map[pycharm_edition].code }}{{ pycharm_version | regex_search('\\d{1,}\\.\\d{1,}') }}/"
    remote_src: true
